// Generated by CoffeeScript 1.3.3
/**
 longurl -- use longurl.com api to get full urls from url-shortening services like bit.ly
 
 Example usage:
   var longurl = require('longurl')
   
   longurl('http://bit.ly/MNwVVo')
   
   var shorturl
   longurl('http://bit.ly/MNwVVo', function(url) { fullurl = url })
   
 
 params
    url String such as http://bit.ly/MNwVVo
    callback(String longurl) where longurl is the full url
    true for console.log or callback verbose(error, resultsObject, body, longurl)
*/

var longurl, request;

request = require('request');

module.exports = longurl = function(url, cb, verbose) {
  if (cb == null) {
    cb = console.log;
  }
  if (verbose == null) {
    verbose = false;
  }
  request.get('http://www.longurlplease.com/api/v1.1?q=' + url, function(err, results, body) {
    var its, k, v;
    if (verbose === true) {
      verbose = console.log;
    }
    its = JSON.parse(body);
    if (verbose) {
      verbose(err, results, body, its);
    }
    cb(((function() {
      var _results;
      _results = [];
      for (k in its) {
        v = its[k];
        _results.push(v);
      }
      return _results;
    })())[0]);
    return its;
  });
  return void 0;
};
